export const ACCOUNT_CARDS = [
  {
    id: 'acc_savings',
    type: 'account',
    accountType: 'savings',
    name: 'Savings Account',
    emoji: '🐷',
    flavor: 'A cozy piggy bank for a rainy day.',
    persistent: true,
  },
  {
    id: 'acc_hysa',
    type: 'account',
    accountType: 'hysa',
    name: 'High-Yield Savings',
    emoji: '🍯',
    flavor: 'Sweeter interest, same safety.',
    persistent: true,
  },
  {
    id: 'acc_cd_1yr',
    type: 'account',
    accountType: 'cd',
    termYears: 1,
    name: 'CD — 1 Year',
    emoji: '🫙',
    flavor: 'Short commitment, modest reward.',
    persistent: true,
  },
  {
    id: 'acc_cd_2yr',
    type: 'account',
    accountType: 'cd',
    termYears: 2,
    name: 'CD — 2 Years',
    emoji: '🫙',
    flavor: 'Lock it away and let it grow.',
    persistent: true,
  },
  {
    id: 'acc_cd_3yr',
    type: 'account',
    accountType: 'cd',
    termYears: 3,
    name: 'CD — 3 Years',
    emoji: '🫙',
    flavor: 'Patience is its own reward.',
    persistent: true,
  },
  {
    id: 'acc_cd_5yr',
    type: 'account',
    accountType: 'cd',
    termYears: 5,
    name: 'CD — 5 Years',
    emoji: '🫙',
    flavor: 'The long game pays off.',
    persistent: true,
  },
  {
    id: 'acc_credit',
    type: 'account',
    accountType: 'credit_card',
    name: 'Credit Card',
    emoji: '🍃',
    flavor: 'Use wisely — it remembers everything.',
    persistent: true,
    requiresCreditScore: 580,
  },
  {
    id: 'acc_roth',
    type: 'account',
    accountType: 'roth_ira',
    name: 'Roth IRA',
    emoji: '🌻',
    flavor: 'Plant seeds today, harvest tax-free.',
    persistent: true,
  },
  {
    id: 'acc_trad',
    type: 'account',
    accountType: 'trad_ira',
    name: 'Traditional IRA',
    emoji: '🌾',
    flavor: 'Reduce taxes now, pay later.',
    persistent: true,
  },
  {
    id: 'acc_brokerage',
    type: 'account',
    accountType: 'brokerage',
    name: 'Brokerage',
    emoji: '🌳',
    flavor: 'No limits. No shelter. No mercy.',
    persistent: true,
  },
];

export const POSITIVE_EVENT_CARDS = [
  {
    id: 'evt_tax_refund',
    type: 'event',
    subtype: 'positive',
    name: 'Tax Refund!',
    emoji: '📬',
    flavor: 'The government owes you one.',
    effect: { type: 'cash', minAmount: 500, maxAmount: 3000 },
  },
  {
    id: 'evt_inheritance',
    type: 'event',
    subtype: 'positive',
    name: 'Inheritance',
    emoji: '🫖',
    flavor: 'Great-aunt Rosemary left you something.',
    effect: { type: 'cash', minAmount: 5000, maxAmount: 20000 },
  },
  {
    id: 'evt_bonus',
    type: 'event',
    subtype: 'positive',
    name: 'Work Bonus',
    emoji: '🎉',
    flavor: 'Your manager finally noticed.',
    effect: { type: 'cash', minAmount: 1000, maxAmount: 5000 },
  },
  {
    id: 'evt_side_hustle',
    type: 'event',
    subtype: 'positive',
    name: 'Side Hustle',
    emoji: '🧺',
    flavor: 'Your Etsy shop is taking off.',
    effect: { type: 'choice', options: [
      { label: '$500/year for 3 years', type: 'recurring', amount: 500, turns: 3 },
      { label: '$1,000 now', type: 'cash', amount: 1000 },
    ]},
  },
  {
    id: 'evt_garage_sale',
    type: 'event',
    subtype: 'positive',
    name: 'Garage Sale',
    emoji: '🏷️',
    flavor: 'One person\'s clutter, your treasure.',
    effect: { type: 'cash', minAmount: 200, maxAmount: 800 },
  },
  {
    id: 'evt_found_money',
    type: 'event',
    subtype: 'positive',
    name: 'Found Money',
    emoji: '🍀',
    flavor: 'An old jacket pocket. Happy birthday.',
    effect: { type: 'cash', minAmount: 50, maxAmount: 500 },
  },
  {
    id: 'evt_freelance',
    type: 'event',
    subtype: 'positive',
    name: 'Freelance Gig',
    emoji: '✍️',
    flavor: 'They loved your portfolio.',
    effect: { type: 'freelance', amount: 1500, selfEmploymentTax: 0.153 },
  },
  {
    id: 'evt_401k_match',
    type: 'event',
    subtype: 'positive',
    name: 'Employer 401k Match',
    emoji: '🤝',
    flavor: 'Free money — if you put in your share.',
    effect: { type: 'retirement_match', matchRate: 0.04 },
    condition: 'hasRetirementAccount',
  },
  {
    id: 'evt_promotion',
    type: 'event',
    subtype: 'positive',
    name: 'Promotion!',
    emoji: '🌟',
    flavor: 'Corner office, corner budget.',
    effect: { type: 'income_increase', minAmount: 5000, maxAmount: 10000 },
  },
  {
    id: 'evt_cashback',
    type: 'event',
    subtype: 'positive',
    name: 'Cashback Milestone',
    emoji: '💌',
    flavor: 'Your card rewards you for existing.',
    effect: { type: 'cash', minAmount: 100, maxAmount: 300 },
    condition: 'hasCreditCard',
  },
  {
    id: 'evt_dividend',
    type: 'event',
    subtype: 'positive',
    name: 'Dividend Payout',
    emoji: '🌼',
    flavor: 'Your investments pay you back.',
    effect: { type: 'dividend', rate: 0.02 },
    condition: 'hasInvestments',
  },
  {
    id: 'evt_windfall_invest',
    type: 'event',
    subtype: 'special',
    name: 'Windfall Investment',
    emoji: '✨',
    flavor: 'A once-in-a-decade opportunity.',
    effect: { type: 'double_speculative' },
  },
];

export const NEGATIVE_EVENT_CARDS = [
  {
    id: 'evt_car_repair',
    type: 'event',
    subtype: 'negative',
    name: 'Car Repair',
    emoji: '🔧',
    flavor: 'The check engine light was not decorative.',
    effect: { type: 'expense', minAmount: 500, maxAmount: 2000 },
  },
  {
    id: 'evt_medical',
    type: 'event',
    subtype: 'negative',
    name: 'Medical Bill',
    emoji: '🏥',
    flavor: 'You didn\'t see that coming. Neither did your wallet.',
    effect: { type: 'expense', minAmount: 1000, maxAmount: 8000 },
  },
  {
    id: 'evt_job_loss',
    type: 'event',
    subtype: 'negative',
    name: 'Job Loss',
    emoji: '📦',
    flavor: 'The layoffs came quietly, like autumn.',
    effect: { type: 'income_zero', turns: 1 },
  },
  {
    id: 'evt_rent_hike',
    type: 'event',
    subtype: 'negative',
    name: 'Rent Hike',
    emoji: '🏠',
    flavor: 'Your landlord\'s renovation: a new coat of prices.',
    effect: { type: 'expense_increase', minAmount: 1200, maxAmount: 3600, category: 'housing', turns: 3 },
  },
  {
    id: 'evt_identity_theft',
    type: 'event',
    subtype: 'negative',
    name: 'Identity Theft',
    emoji: '🎭',
    flavor: 'Someone has been living your best life.',
    effect: { type: 'multi', effects: [
      { type: 'expense', amount: 500 },
      { type: 'credit_score', delta: -30 },
    ]},
  },
  {
    id: 'evt_market_crash',
    type: 'event',
    subtype: 'negative',
    name: 'Market Crash',
    emoji: '📉',
    flavor: 'The forest floor after a storm.',
    effect: { type: 'market_loss', lossMin: 0.20, lossMax: 0.35 },
  },
  {
    id: 'evt_pet_emergency',
    type: 'event',
    subtype: 'negative',
    name: 'Pet Emergency',
    emoji: '🐾',
    flavor: 'Biscuit ate something she shouldn\'t have.',
    effect: { type: 'expense', minAmount: 800, maxAmount: 3000 },
  },
  {
    id: 'evt_car_totaled',
    type: 'event',
    subtype: 'negative',
    name: 'Car Totaled',
    emoji: '🚗',
    flavor: 'The deer won.',
    effect: { type: 'expense', minAmount: 8000, maxAmount: 20000 },
  },
  {
    id: 'evt_legal',
    type: 'event',
    subtype: 'negative',
    name: 'Legal Dispute',
    emoji: '⚖️',
    flavor: 'Your neighbor, the fence, and 3 months of letters.',
    effect: { type: 'expense', minAmount: 1000, maxAmount: 5000 },
  },
  {
    id: 'evt_inflation',
    type: 'event',
    subtype: 'negative',
    name: 'Inflation Surge',
    emoji: '🎈',
    flavor: 'Everything costs more. No one knows why.',
    effect: { type: 'expense_pct_increase', pct: 0.08, turns: 1 },
  },
];

export const SPECIAL_CARDS = [
  {
    id: 'spc_refinance',
    type: 'event',
    subtype: 'special',
    name: 'Refinance',
    emoji: '📋',
    flavor: 'Better terms for a better you.',
    effect: { type: 'refinance' },
    requiresCreditScore: 680,
  },
  {
    id: 'spc_advisor',
    type: 'event',
    subtype: 'special',
    name: 'Financial Advisor',
    emoji: '🦉',
    flavor: 'The owl knows what\'s coming.',
    effect: { type: 'peek_next_turn' },
  },
  {
    id: 'spc_emergency_reward',
    type: 'event',
    subtype: 'special',
    name: 'Emergency Fund Reward',
    emoji: '🛡️',
    flavor: 'Your past self prepared for this.',
    effect: { type: 'skip_next_negative' },
    condition: 'emergencyFundBuilt',
  },
  {
    id: 'spc_credit_boost',
    type: 'event',
    subtype: 'special',
    name: 'Credit Score Boost',
    emoji: '⭐',
    flavor: 'A dispute resolved in your favor.',
    effect: { type: 'credit_score', delta: 25 },
  },
];

export function buildFullDeck() {
  const deck = [];
  const accountPool = [...ACCOUNT_CARDS, ...ACCOUNT_CARDS];
  const positivePool = [...POSITIVE_EVENT_CARDS];
  const negativePool = [...NEGATIVE_EVENT_CARDS];
  const specialPool = [...SPECIAL_CARDS];

  deck.push(...accountPool);
  deck.push(...positivePool);
  deck.push(...negativePool);
  deck.push(...specialPool);

  return shuffle(deck);
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
